### ISSUE TITLE
Only supports a single camera

### ISSUE THREAD

**Issue by andypiper** [gamalsherif1/CamPeek#3]
I noticed when I plugged in a USB camera that CamPeek only shows the built-in camera and there is no way to have it switch to a different one. GNOME Cameras does allow me to switch between cameras. A simple solution would be to have a menu from the extension item to switch between a list of known cameras.

**Comment by gamalsherif1** [comment]
Good point — adding support for switching between available cameras from the menu makes sense. I’ll plan to implement that.
Thank you for the support

**Comment by gamalsherif1** [comment]
the new version is now available , give it a try ! @andypiper

**Comment by andypiper** [comment]
Yeah, I like the menu! The problem is that I think it is not finding the additional camera, and in fact I think it is falling into the "no camera so default option" code because it only shows "Default Camera" in the menu. Refresh is not making a difference there. 

`journalctl` shows

May 08 16:22:38 neshatan gnome-shell[3415]: Error fixing menu position: TypeError: this.menu._boxPointer._arrowOrigin.set_x_align is not a function
                                            _fixMenuPosition@file:///home/andypiper/.local/share/gnome-shell/extensions/CamPeek@gamalsherif1.github.io/extension.js:448:46
                                            _scheduleMenuPositionFix/id<@file:///home/andypiper/.local/share/gnome-shell/extensions/CamPeek@gamalsherif1.github.io/extension.js:400:14
                                            @resource:///org/gnome/shell/ui/init.js:21:20

May 08 16:22:39 neshatan gnome-shell[223905]: Redistribute latency...

I don't think those relate to the multicamera lookup though, that seems to happen when the camera preview window is opened.

```
$ ls /dev/video*
/dev/video0  /dev/video1  /dev/video2  /dev/video3
```

So there is definitely more than one camera available, and GNOME Camera sees both.

**Comment by gamalsherif1** [comment]
The problem is now fixed . the new version of 'CamPeek' is live at gnome extensions!
try it and let me know ! @andypiper

**Comment by andypiper** [comment]
This now finds multiple cameras! 🎉
Unfortunately it shows all video devices including those that are not usable.
It also does not work with the valid secondary devices (says they are in use, when they are not).

**Comment by gamalsherif1** [comment]
I've added the following improvements:

## 1. Smart Camera Detection  
- The extension now actively tests each camera using GStreamer before showing it in the menu.  
- Only devices that GStreamer can successfully open will appear — including virtual cameras, but **only if they’re actively streaming**.  
- It also auto-selects the first working device on first run, saving users from manually trial-and-erroring cameras.

## 2. Cleaner Camera Menu  
- The camera menu now filters out non-functional or disconnected devices.  
- No more ghost entries or “in use” errors from inactive or broken cameras.  
- Virtual devices like `v4l2loopback` are only shown if they’re actively streaming data.

I hope this update resolves the issue!  
If you’re still seeing devices show up as “in use” or behaving oddly, it’s likely due to how the system (GNOME 48 / Ubuntu 25.04) handles video devices under the hood — the extension just builds on top of that.

🔄 The update has already been pushed to the GitHub repo and is currently under review on the GNOME Extensions website.

**Comment by andypiper** [comment]
I feel like this is really close! But for some reason, it is still not working with my secondary camera (although GNOME Camera aka Snapshot, works with both, but that is written in Rust and I don't speak Rust...)

Currently it does show that it is dynamically loading the device list when I open the menu, then displays them.

![Image](https://github.com/user-attachments/assets/e02e69e5-02b2-48fa-98e8-83ea37db5323)

Again, I believe only `/dev/video0` and `/dev/video2` are the actual camera devices, with the others being the metadata device nodes.

I tried some GStreamer command line stuff to get simple commands to stream from each camera.

Firstly, the discovery output:

```text
$ gst-device-monitor-1.0 Video/Source
Probing devices...


Device found:

        name  : Laptop Webcam Module (2nd Gen) (V4L2)
        class : Video/Source
        caps  : image/jpeg, width=1920, height=1080, framerate=30/1
                image/jpeg, width=1280, height=720, framerate=30/1
                image/jpeg, width=640, height=480, framerate=30/1
                image/jpeg, width=640, height=360, framerate=30/1
                video/x-raw, format=YUY2, interlace-mode=progressive, width=640, height=480, framerate=30/1
                video/x-raw, format=YUY2, interlace-mode=progressive, width=640, height=360, framerate=30/1
        properties:
                is-default = true
                api.v4l2.cap.bus_info = usb-0000:c3:00.0-3
                api.v4l2.cap.capabilities = 84a00001
                api.v4l2.cap.card = Laptop Webcam Module (2nd Gen):
                api.v4l2.cap.device-caps = 04200001
                api.v4l2.cap.driver = uvcvideo
                api.v4l2.cap.version = 6.14.5
                api.v4l2.path = /dev/video0
                device.api = v4l2
                device.devids = [ 20736 ]
                device.id = 54
                device.product.id = 0x001c
                device.vendor.id = 0x32ac
                factory.name = api.v4l2.source
                media.class = Video/Source
                node.description = Laptop Webcam Module (2nd Gen) (V4L2)
                node.name = v4l2_input.pci-0000_c3_00.0-usb-0_3_1.0
                node.nick = Laptop Webcam Module (2nd Gen)
                node.pause-on-idle = false
                object.path = v4l2:/dev/video0
                priority.session = 1000
                factory.id = 11
                client.id = 41
                clock.quantum-limit = 8192
                node.loop.name = data-loop.0
                media.role = Camera
                node.driver = true
                object.id = 72
                object.serial = 72
        gst-launch-1.0 pipewiresrc target-object=72 ! ...


Device found:

        name  : Opal Tadpole (V4L2)
        class : Video/Source
        caps  : image/jpeg, width=1920, height=1080, framerate={ (fraction)30/1, (fraction)24/1 }
                image/jpeg, width=1280, height=720, framerate={ (fraction)30/1, (fraction)24/1 }
        properties:
                is-default = false
                api.v4l2.cap.bus_info = usb-0000:c3:00.0-2
                api.v4l2.cap.capabilities = 84a00001
                api.v4l2.cap.card = Opal Tadpole: Opal Tadpole
                api.v4l2.cap.device-caps = 04200001
                api.v4l2.cap.driver = uvcvideo
                api.v4l2.cap.version = 6.14.5
                api.v4l2.path = /dev/video2
                device.api = v4l2
                device.devids = [ 20738 ]
                device.id = 70
                device.product.id = 0x0002
                device.vendor.id = 0x3673
                factory.name = api.v4l2.source
                media.class = Video/Source
                node.description = Opal Tadpole (V4L2)
                node.name = v4l2_input.pci-0000_c3_00.0-usb-0_2_1.0
                node.nick = Opal Tadpole
                node.pause-on-idle = false
                object.path = v4l2:/dev/video2
                priority.session = 980
                factory.id = 11
                client.id = 41
                clock.quantum-limit = 8192
                node.loop.name = data-loop.0
                media.role = Camera
                node.driver = true
                object.id = 209
                object.serial = 476
        gst-launch-1.0 pipewiresrc target-object=476 ! ...
```

From this, I assume you could potentially use `node.nick` as a friendly name for the devices.

OK, now to get video from these... I tried pipewiresrc and that does not work, but it does work with v4l2:

`gst-launch-1.0 pipewiresrc target-object=476 ! decodebin ! videoconvert ! autovideosink`
(fails)

`gst-launch-1.0 v4l2src device=/dev/video0 ! decodebin ! videoconvert ! autovideosink`
`gst-launch-1.0 v4l2src device=/dev/video0 ! decodebin ! videoconvert ! autovideosink`

(these both work)

I can resize the stream to the smaller of the two supported sizes (caps) for the Tadpole, but the 720 is still fairly large.

`gst-launch-1.0 v4l2src device=/dev/video2 ! image/jpeg,width=1280,height=720,framerate=30/1 ! jpegdec ! videoconvert ! autovideosink`

Here, the built-in Framework camera supports 4 different sizes, but the smallest ones are arguably too small for a useful desktop preview on a hi-dpi screen!

**Comment by andypiper** [comment]
Ah! This is 23 right now. I'll wait for the review on e.g.o 👍🏻

**Comment by andypiper** [comment]
OK, so I'm still using v 23 but I have some new data to share.

This is working in my home office setup where I have my Framework plugged in with the lid closed, and a second camera (Logitech Streamcam) plugged in via a CalDigit TB4 dock.

I can use the menu to select `/dev/video2` and I get the image 👍🏻 

I realise that v 24 has more changes still to test, but it looks like this is all heading in a great direction.

(It is great anyway, just wanted to share the status)

Here's the info for this setup, in case it is useful. I noticed that the Streamcam seems to have a lot more caps available than the Tadpole advertises!

```text
$ gst-device-monitor-1.0 Video/Source
Probing devices...


Device found:

        name  : Laptop Webcam Module (2nd Gen) (V4L2)
        class : Video/Source
        caps  : image/jpeg, width=1920, height=1080, framerate=30/1
                image/jpeg, width=1280, height=720, framerate=30/1
                image/jpeg, width=640, height=480, framerate=30/1
                image/jpeg, width=640, height=360, framerate=30/1
                video/x-raw, format=YUY2, interlace-mode=progressive, width=640, height=480, framerate=30/1
                video/x-raw, format=YUY2, interlace-mode=progressive, width=640, height=360, framerate=30/1
        properties:
                is-default = true
                api.v4l2.cap.bus_info = usb-0000:c3:00.0-3
                api.v4l2.cap.capabilities = 84a00001
                api.v4l2.cap.card = Laptop Webcam Module (2nd Gen):
                api.v4l2.cap.device-caps = 04200001
                api.v4l2.cap.driver = uvcvideo
                api.v4l2.cap.version = 6.14.5
                api.v4l2.path = /dev/video0
                device.api = v4l2
                device.devids = [ 20736 ]
                device.id = 58
                device.product.id = 0x001c
                device.vendor.id = 0x32ac
                factory.name = api.v4l2.source
                media.class = Video/Source
                node.description = Laptop Webcam Module (2nd Gen) (V4L2)
                node.name = v4l2_input.pci-0000_c3_00.0-usb-0_3_1.0
                node.nick = Laptop Webcam Module (2nd Gen)
                node.pause-on-idle = false
                object.path = v4l2:/dev/video0
                priority.session = 1000
                factory.id = 11
                client.id = 41
                clock.quantum-limit = 8192
                node.loop.name = data-loop.0
                media.role = Camera
                node.driver = true
                object.id = 106
                object.serial = 107
        gst-launch-1.0 pipewiresrc target-object=107 ! ...


Device found:

        name  : Logitech StreamCam (V4L2)
        class : Video/Source
        caps  : video/x-raw, format=YUY2, interlace-mode=progressive, width=640, height=480, framerate={ (fraction)30/1, (fraction)24/1, (fraction)20/1, (fraction)15/1, (fraction)10/1, (fraction)15/2, (fraction)5/1 }
                video/x-raw, format=YUY2, interlace-mode=progressive, width=176, height=144, framerate={ (fraction)30/1, (fraction)24/1, (fraction)20/1, (fraction)15/1, (fraction)10/1, (fraction)15/2, (fraction)5/1 }
                video/x-raw, format=YUY2, interlace-mode=progressive, width=320, height=240, framerate={ (fraction)30/1, (fraction)24/1, (fraction)20/1, (fraction)15/1, (fraction)10/1, (fraction)15/2, (fraction)5/1 }
                video/x-raw, format=YUY2, interlace-mode=progressive, width=424, height=240, framerate={ (fraction)30/1, (fraction)24/1, (fraction)20/1, (fraction)15/1, (fraction)10/1, (fraction)15/2, (fraction)5/1 }
                video/x-raw, format=YUY2, interlace-mode=progressive, width=640, height=360, framerate={ (fraction)30/1, (fraction)24/1, (fraction)20/1, (fraction)15/1, (fraction)10/1, (fraction)15/2, (fraction)5/1 }
                video/x-raw, format=YUY2, interlace-mode=progressive, width=848, height=480, framerate={ (fraction)30/1, (fraction)24/1, (fraction)20/1, (fraction)15/1, (fraction)10/1, (fraction)15/2, (fraction)5/1 }
                video/x-raw, format=YUY2, interlace-mode=progressive, width=960, height=540, framerate={ (fraction)30/1, (fraction)24/1, (fraction)20/1, (fraction)15/1, (fraction)10/1, (fraction)15/2, (fraction)5/1 }
                video/x-raw, format=YUY2, interlace-mode=progressive, width=1280, height=720, framerate={ (fraction)30/1, (fraction)24/1, (fraction)20/1, (fraction)15/1, (fraction)10/1, (fraction)15/2, (fraction)5/1 }
                video/x-raw, format=YUY2, interlace-mode=progressive, width=1600, height=896, framerate={ (fraction)30/1, (fraction)24/1, (fraction)20/1, (fraction)15/1, (fraction)10/1, (fraction)15/2, (fraction)5/1 }
                video/x-raw, format=YUY2, interlace-mode=progressive, width=1920, height=1080, framerate={ (fraction)30/1, (fraction)24/1, (fraction)20/1, (fraction)15/1, (fraction)10/1, (fraction)15/2, (fraction)5/1 }
                video/x-raw, format=YUY2, interlace-mode=progressive, width=2304, height=1296, framerate=5/1
                image/jpeg, width=640, height=480, framerate={ (fraction)60/1, (fraction)30/1, (fraction)24/1, (fraction)20/1, (fraction)15/1, (fraction)10/1, (fraction)15/2, (fraction)5/1 }
                image/jpeg, width=176, height=144, framerate={ (fraction)60/1, (fraction)30/1, (fraction)24/1, (fraction)20/1, (fraction)15/1, (fraction)10/1, (fraction)15/2, (fraction)5/1 }
                image/jpeg, width=320, height=240, framerate={ (fraction)60/1, (fraction)30/1, (fraction)24/1, (fraction)20/1, (fraction)15/1, (fraction)10/1, (fraction)15/2, (fraction)5/1 }
                image/jpeg, width=424, height=240, framerate={ (fraction)60/1, (fraction)30/1, (fraction)24/1, (fraction)20/1, (fraction)15/1, (fraction)10/1, (fraction)15/2, (fraction)5/1 }
                image/jpeg, width=640, height=360, framerate={ (fraction)60/1, (fraction)30/1, (fraction)24/1, (fraction)20/1, (fraction)15/1, (fraction)10/1, (fraction)15/2, (fraction)5/1 }
                image/jpeg, width=848, height=480, framerate={ (fraction)60/1, (fraction)30/1, (fraction)24/1, (fraction)20/1, (fraction)15/1, (fraction)10/1, (fraction)15/2, (fraction)5/1 }
                image/jpeg, width=960, height=540, framerate={ (fraction)60/1, (fraction)30/1, (fraction)24/1, (fraction)20/1, (fraction)15/1, (fraction)10/1, (fraction)15/2, (fraction)5/1 }
                image/jpeg, width=1280, height=720, framerate={ (fraction)60/1, (fraction)30/1, (fraction)24/1, (fraction)20/1, (fraction)15/1, (fraction)10/1, (fraction)15/2, (fraction)5/1 }
                image/jpeg, width=1600, height=896, framerate={ (fraction)60/1, (fraction)30/1, (fraction)24/1, (fraction)20/1, (fraction)15/1, (fraction)10/1, (fraction)15/2, (fraction)5/1 }
                image/jpeg, width=1920, height=1080, framerate={ (fraction)60/1, (fraction)30/1, (fraction)24/1, (fraction)20/1, (fraction)15/1, (fraction)10/1, (fraction)15/2, (fraction)5/1 }
                video/x-raw, format=NV12, interlace-mode=progressive, width=640, height=480, framerate={ (fraction)30/1, (fraction)24/1, (fraction)20/1, (fraction)15/1, (fraction)10/1, (fraction)15/2, (fraction)5/1 }
                video/x-raw, format=NV12, interlace-mode=progressive, width=640, height=360, framerate={ (fraction)30/1, (fraction)24/1, (fraction)20/1, (fraction)15/1, (fraction)10/1, (fraction)15/2, (fraction)5/1 }
                video/x-raw, format=NV12, interlace-mode=progressive, width=1280, height=720, framerate={ (fraction)30/1, (fraction)24/1, (fraction)20/1, (fraction)15/1, (fraction)10/1, (fraction)15/2, (fraction)5/1 }
                video/x-raw, format=NV12, interlace-mode=progressive, width=1920, height=1080, framerate={ (fraction)30/1, (fraction)24/1, (fraction)20/1, (fraction)15/1, (fraction)10/1, (fraction)15/2, (fraction)5/1 }
        properties:
                is-default = false
                api.v4l2.cap.bus_info = usb-0000:c3:00.4-1.4.3
                api.v4l2.cap.capabilities = 84a00001
                api.v4l2.cap.card = Logitech StreamCam
                api.v4l2.cap.device-caps = 04200001
                api.v4l2.cap.driver = uvcvideo
                api.v4l2.cap.version = 6.14.5
                api.v4l2.path = /dev/video2
                device.api = v4l2
                device.devids = [ 20738 ]
                device.id = 205
                device.product.id = 0x0893
                device.vendor.id = 0x046d
                factory.name = api.v4l2.source
                media.class = Video/Source
                node.description = Logitech StreamCam (V4L2)
                node.name = v4l2_input.pci-0000_c3_00.4-usb-0_1.4.3_1.0
                node.nick = Logitech StreamCam
                node.pause-on-idle = false
                object.path = v4l2:/dev/video2
                priority.session = 980
                factory.id = 11
                client.id = 41
                clock.quantum-limit = 8192
                node.loop.name = data-loop.0
                media.role = Camera
                node.driver = true
                object.id = 249
                object.serial = 1025
        gst-launch-1.0 pipewiresrc target-object=1025 ! ...
```

**Comment by gamalsherif1** [comment]
the new Version is live now !

**Comment by andypiper** [comment]
Works! ... except not with this Opal Tadpole. It detects it, says it is working, but then when it tries to display it, there's an error:

```
May 13 11:33:38 neshatan gnome-shell[109108]: Setting pipeline to PAUSED ...
May 13 11:33:38 neshatan gnome-shell[109108]: Pipeline is live and does not need PREROLL ...
May 13 11:33:38 neshatan gnome-shell[109108]: Pipeline is PREROLLED ...
May 13 11:33:38 neshatan gnome-shell[109108]: Setting pipeline to PLAYING ...
May 13 11:33:38 neshatan gnome-shell[109108]: New clock: GstSystemClock
May 13 11:33:38 neshatan gnome-shell[109108]: ERROR: from element /GstPipeline:pipeline0/GstV4l2Src:v4l2src0: Internal data stream error.
May 13 11:33:38 neshatan gnome-shell[109108]: Additional debug info:
May 13 11:33:38 neshatan gnome-shell[109108]: ../libs/gst/base/gstbasesrc.c(3187): gst_base_src_loop (): /GstPipeline:pipeline0/GstV4l2Src:v4l2src0:
May 13 11:33:38 neshatan gnome-shell[109108]: streaming stopped, reason not-negotiated (-4)
May 13 11:33:38 neshatan gnome-shell[109108]: Execution ended after 0:00:00.001035819
May 13 11:33:38 neshatan gnome-shell[109108]: Setting pipeline to NULL ...
May 13 11:33:38 neshatan gnome-shell[109108]: Freeing pipeline ...
May 13 11:33:38 neshatan gnome-shell[4225]: CamPeek: Menu position updated
May 13 11:33:53 neshatan kernel: usb 3-2: USB disconnect, device number 5
```

My suspicion is that this is specific to this camera and related to the size of the requested stream, but I am not completely sure on that.

Anyway, this is great, I have it now working with my desk setup (Logitech Streamcam, with my built-in laptop camera not shown when the lid is closed).

I think the only other small thing that this feature can benefit from is a user-friendly name in the menu instead of the video device path, but otherwise, this is good. Thanks so much for all your work and putting up with my issues here!!

**Comment by andypiper** [comment]
Sorry, I'm reopening 🙈 

This is no longer working with the built-in camera on the Framework, or the Tadpole, only the Logitech Streamcam 🙁

**Comment by gamalsherif1** [comment]
Sorry to hear that , and thank you for reopening the issue.
At the moment, I’m reverting the extension to the previous update because I’m currently in the middle of my final exams and busy with my graduation project. I really appreciate your patience, and I’ll look into this more deeply as soon as I’m able to.

**Comment by andypiper** [comment]
I really appreciate *you*, and you should totally focus on the things you need to do! 🙏🏻
